name: Maven Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Running Test Automation Framework with Maven
        run: mvn test -X -Dbrowser=chrome -DisLambdaTest=true -DisHeadless=false

      - name: Upload Test Logs
        if: always()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Test logs
          path: logs/

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: HTML-reports
          path: report.html

      - name: Upload screenshots as Artifacts
        if: always()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: screenshots
          path: screenshots/

      - name: Prepare reports for deployment
        if: always()
        run: |
          mkdir -p public/extent-reports
          cp -R report.html public/extent-reports/
          cp -R screenshots/ public/extent-reports/screenshots/

      - name: Deploy reports to GitHub Pages
        if: always()
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public/extent-reports
          token: ${{ secrets.PAT }}
          clean: true
